version: '3.7'
services:
    zahlung-db:
        image: postgres:latest
        container_name: umoc-db
        restart: unless-stopped
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: umoc
        ports:
            - "5432:5432"